-- V_04

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS AGENT(
  ID uuid DEFAULT gen_random_uuid(),
  USER_ID VARCHAR(255) NOT NULL,
  ORGANIZATION_ID VARCHAR(255) NOT NULL,
  LOGIN_ID VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  DISPLAY_NAME VARCHAR(255) NOT NULL,
  EMAIL_ID VARCHAR(255) NOT NULL,
  PROFILE_ID VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMER_INFO(
  ID uuid DEFAULT gen_random_uuid(),
  ACCOUNT_ID VARCHAR(255) NOT NULL,
  EMAIL_ADDRESS VARCHAR(255) NOT NULL,
  ANI VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ORCHESTRATION_CONTEXT(
  ID uuid DEFAULT gen_random_uuid(),
  CONTEXT_QUEUE VARCHAR(255) NOT NULL,
  USER_ID VARCHAR(255) NOT NULL,
  CHANNEL_PROVIDER_ID VARCHAR(255) NOT NULL,
  CHANNEL_PROVIDER_ADDRESS VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
); 

CREATE TABLE IF NOT EXISTS QUESTION(
  ID uuid DEFAULT gen_random_uuid(),
  EXTERNAL_ID VARCHAR(255) NOT NULL,
  QUESTION_ORDER INTEGER NOT NULL,
  QUESTION_NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS ATTRIBUTE_LIST(
  ID uuid DEFAULT gen_random_uuid(),
  ORCHESTRATION_CONTEXT_ID uuid NOT NULL,
  ATTRIBUTE_VALUE VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(ORCHESTRATION_CONTEXT_ID) REFERENCES ORCHESTRATION_CONTEXT(ID)
);

CREATE TABLE IF NOT EXISTS SURVEY_CONTEXT(
  ID uuid DEFAULT gen_random_uuid(),
  CUSTOMER_INFO_ID uuid NOT NULL,
  AGENT_ID uuid NOT NULL,
  ORCHESTRATION_CONTEXT_ID uuid NOT NULL,
  TENTANT_ID VARCHAR(255) NOT NULL,
  LAST_AGENT_ID VARCHAR(255) NOT NULL,
  CALL_ID VARCHAR(255) NOT NULL,
  DNIS VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(CUSTOMER_INFO_ID) REFERENCES CUSTOMER_INFO(ID),
  FOREIGN KEY(AGENT_ID) REFERENCES AGENT(ID),
  FOREIGN KEY(ORCHESTRATION_CONTEXT_ID) REFERENCES ORCHESTRATION_CONTEXT(ID)
);

CREATE TABLE IF NOT EXISTS SURVEY(
  ID uuid DEFAULT gen_random_uuid(),
  SURVEY_CONTEXT_ID uuid NOT NULL,
  ENGAGEMENT_ID VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  LANGUAGE VARCHAR(255) NOT NULL,
  CHANNEL_ID VARCHAR(255) NOT NULL,
  REASON VARCHAR(255) NOT NULL,
  START_DATE TIMESTAMPTZ NOT NULL,
  END_DATE TIMESTAMPTZ NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(SURVEY_CONTEXT_ID) REFERENCES SURVEY_CONTEXT(ID)
);

CREATE TABLE IF NOT EXISTS SURVEY_QUESTION(
  SURVEY_ID uuid NOT NULL,
  QUESTION_ID uuid NOT NULL,
  PRIMARY KEY(SURVEY_ID, QUESTION_ID),
  FOREIGN KEY(SURVEY_ID) REFERENCES SURVEY(ID),
  FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(ID)
);

CREATE TABLE IF NOT EXISTS QUESTION_OPTION(
  ID uuid DEFAULT gen_random_uuid(),
  QUESTION_ID uuid NOT NULL,
  EXTERNAL_ID VARCHAR(255) NOT NULL,
  OPTION_VALUE INTEGER NOT NULL,
  RESULT VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(QUESTION_ID) REFERENCES QUESTION(ID)
);

CREATE TABLE IF NOT EXISTS ANSWER(
  ID uuid DEFAULT gen_random_uuid(),
  SURVEY_ID uuid NOT NULL,
  QUESTION_OPTION_ID uuid NOT NULL,
  EXTERNAL_ID VARCHAR(255) NOT NULL,
  ANSWER_TYPE VARCHAR(255) NOT NULL,
  RESULT VARCHAR(255) NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY(SURVEY_ID) REFERENCES SURVEY(ID), 
  FOREIGN KEY(QUESTION_OPTION_ID) REFERENCES QUESTION_OPTION(ID)
);
