logging:
    level:
        org.springframework.jdbc.core: DEBUG


spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://spike01-postgres.postgres.database.azure.com:5432/postgres?sslmode=require
        username: pgadmin
        password: Avaya123!
        # azure:
        #     passwordless-enabled: true 
        dbcp2:
            max-wait-millis: 30000
            validation-query: select 1
            validation-query-timeout: 30
    jpa:
        show-sql: false
        open-in-view: false
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
    sql:
        init:
            mode: always
