logging:
    level:
        org.springframework.jdbc.core: DEBUG
        
server:
    port: 3000

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://yb-tservers:5433/yugabyte
        username: yugabyte
        password: yugabyte
        hikari:
            connection-timeout: 2000
            initialization-fail-timeout: 0
        dbcp2:
            max-wait-millis: 30000
            validation-query: select 1
            validation-query-timeout: 30
    jpa:
        show-sql: false
        open-in-view: false
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: 'liveness,readiness'

# pgadmin/Avaya123!