server:
    port: 3000

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/yugabyte
        username: yugabyte
        password: yugabyte
        dbcp2:
            max-wait-millis: 30000
            validation-query: select 1
            validation-query-timeout: 30
    jpa:
        show-sql: false
        open-in-view: false
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none


# pgadmin/Avaya123!